# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Utah Data Science
email: utahdatascience@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Utah County Data Sciency Meetup is a group that provides training and
  networking to local data science practictioners.  This is means
  people interested in analysis, mathematics, statitistics, data engineering,
  and applying these things to full systems are all welcome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Utah-Data-Science.github.io" # the base hostname & protocol for your site
twitter_username: drichards
github_username:  Utah-Data-Science

# Build settings
markdown: kramdown
